# Generated by Django 4.2.7 on 2023-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sprite",
                    models.ImageField(blank=True, null=True, upload_to="Sprites/"),
                ),
                ("num_abilities", models.PositiveIntegerField(default=0)),
                ("url_pokemon", models.URLField(null=True)),
            ],
        ),
    ]
