# Generated by Django 4.2.7 on 2023-11-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_app", "0002_alter_pokemon_sprite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_main_series", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PokemonFormSprites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_default", models.CharField(max_length=255)),
                ("front_shiny", models.CharField(max_length=255)),
                ("back_default", models.CharField(max_length=255)),
                ("back_shiny", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PokemonSprites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_default", models.CharField(max_length=255)),
                ("front_shiny", models.CharField(max_length=255)),
                ("front_female", models.CharField(max_length=255)),
                ("front_shiny_female", models.CharField(max_length=255)),
                ("back_default", models.CharField(max_length=255)),
                ("back_shiny", models.CharField(max_length=255)),
                ("back_female", models.CharField(max_length=255)),
                ("back_shiny_female", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="base_experience",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="is_default",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="location_area_encounters",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="weight",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name="PokemonForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(null=True)),
                ("form_order", models.PositiveIntegerField(null=True)),
                ("is_default", models.BooleanField(null=True)),
                ("is_battle_only", models.BooleanField(null=True)),
                ("is_mega", models.BooleanField(null=True)),
                ("form_name", models.CharField(max_length=255)),
                (
                    "sprites",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemon_app.pokemonformsprites",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_hidden", models.BooleanField(null=True)),
                ("slot", models.PositiveIntegerField(null=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pokemon_app.ability",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="abilities",
            field=models.ManyToManyField(to="pokemon_app.pokemonability"),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="forms",
            field=models.ManyToManyField(to="pokemon_app.pokemonform"),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="sprites",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_app.pokemonsprites",
            ),
        ),
    ]
