# Generated by Django 4.2.7 on 2023-11-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_app", "0004_alter_pokemonability_ability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonsprites",
            name="back_default",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="back_female",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="back_shiny",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="back_shiny_female",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="front_default",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="front_female",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="front_shiny",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonsprites",
            name="front_shiny_female",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
