# Generated by Django 4.2.7 on 2023-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_app", "0005_alter_pokemonsprites_back_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonformsprites",
            name="back_default",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonformsprites",
            name="back_shiny",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonformsprites",
            name="front_default",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonformsprites",
            name="front_shiny",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
