# Generated by Django 4.2.7 on 2023-11-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_app", "0006_alter_pokemonformsprites_back_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonability",
            name="ability",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_app.ability",
            ),
        ),
    ]
