# Generated by Django 4.2.7 on 2023-11-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_app", "0007_alter_pokemonability_ability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonform",
            name="form_order",
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonform",
            name="order",
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
